development:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] || 'mongodb://localhost:27017/mysms_dev' %>
      options:
        retry_writes: true

test:
  clients:
    default:
      uri: <%= ENV.fetch('MONGODB_URI_TEST', 'mongodb://localhost:27017/mysms_test') %>

production:
  clients:
    default:
      uri: <%= ENV.fetch('MONGODB_URI') %>
      options:
        retry_writes: true
